### ISSUE TITLE
h5py on prod envs may need to be pinned down to <3.2

### ISSUE THREAD

**Issue by pavankum** [openforcefield/qca-dataset-submission#285]
I had hit an issue similar to [this](https://github.com/h5py/h5py/issues/1880), pinning h5py version to <3.2 worked well. This might be sporadic since no one else complained about qm-managers erroring out. Here's the traceback from my managers with hdf5 1.10.6 and h5py 3.3.0 when using the current yaml files for a qm worker,
```
Traceback (most recent call last):
  File "/miniconda3/envs/qcarchive-worker-openff-psi4-02-11-22/bin/qcfractal-manager", line 7, in <module>
    from qcfractal.cli.qcfractal_manager import main
  File "/miniconda3/envs/qcarchive-worker-openff-psi4-02-11-22/lib/python3.8/site-packages/qcfractal/__init__.py", line 5, in <module>
    from . import interface
  File "/miniconda3/envs/qcarchive-worker-openff-psi4-02-11-22/lib/python3.8/site-packages/qcfractal/interface/__init__.py", line 5, in <module>
    from . import collections, data, models, util
  File "/miniconda3/envs/qcarchive-worker-openff-psi4-02-11-22/lib/python3.8/site-packages/qcfractal/interface/collections/__init__.py", line 7, in <module>
    from .dataset_view import DatasetView, HDF5View, PlainTextView, RemoteView
  File "/miniconda3/envs/qcarchive-worker-openff-psi4-02-11-22/lib/python3.8/site-packages/qcfractal/interface/collections/dataset_view.py", line 14, in <module>
    import h5py
  File "/miniconda3/envs/qcarchive-worker-openff-psi4-02-11-22/lib/python3.8/site-packages/h5py/__init__.py", line 33, in <module>
    from . import version
  File "/miniconda3/envs/qcarchive-worker-openff-psi4-02-11-22/lib/python3.8/site-packages/h5py/version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py/h5.pyx", line 1, in init h5py.h5
ImportError: /miniconda3/envs/qcarchive-worker-openff-psi4-02-11-22/lib/python3.8/site-packages/h5py/defs.cpython-38-x86_64-linux-gnu.so: undefined symbol: H5Pset_fapl_ros3
```

**Comment by mattwthompson** [comment]
I think environments are now using newer versions
