### ISSUE TITLE
Resubmit Error Jobs in [OpenFF Optimizaiton Set 1]

### ISSUE THREAD

**Issue by yudongqiu** [openforcefield/qca-dataset-submission#6]
The OptimizationDataset [OpenFF Optimizaiton Set 1] has some errors:

![image](https://user-images.githubusercontent.com/6952367/60374050-5bd10280-99b7-11e9-8283-f92c7490447b.png)

Last time I checked the error messages and found that all of them are Psi4 crashes. Resubmitting these jobs may help solve them.

**Comment by dgasmith** [comment]
I built a custom queue and computed these myself. ~3 left at the moment. Please check their errors if you have a moment.

**Comment by yudongqiu** [comment]
Wow this is great! I just confirmed that now 934 are "COMPLETE" and 2 "IMCOMPLETE" and 1 "ERROR". The one error seems to be still from manage not configured correctly:
```
geomeTRIC run_json error:
Traceback (most recent call last):
  File "/home/chodera/miniconda/envs/snowflake/lib/python3.7/site-packages/geometric/run_json.py", line 214, in geometric_run_json
    geometric.optimize.Optimize(coords, M, IC, engine, None, params)
  File "/home/chodera/miniconda/envs/snowflake/lib/python3.7/site-packages/geometric/optimize.py", line 1331, in Optimize
    return optimizer.optimizeGeometry()
  File "/home/chodera/miniconda/envs/snowflake/lib/python3.7/site-packages/geometric/optimize.py", line 1293, in optimizeGeometry
    self.calcEnergyForce()
  File "/home/chodera/miniconda/envs/snowflake/lib/python3.7/site-packages/geometric/optimize.py", line 1002, in calcEnergyForce
    spcalc = self.engine.calc(self.X, self.dirname)
  File "/home/chodera/miniconda/envs/snowflake/lib/python3.7/site-packages/geometric/engine.py", line 873, in calc
    return self.calc_new(coords, dirname)
  File "/home/chodera/miniconda/envs/snowflake/lib/python3.7/site-packages/geometric/engine.py", line 865, in calc_new
    raise QCEngineAPIEngineError("QCEngineAPI computation did not execute correctly. Message: " + ret["error"]["error_message"])
geometric.errors.QCEngineAPIEngineError: QCEngineAPI computation did not execute correctly. Message: QCEngine Resource Error: Psi4 version '' not understood.
```

**Comment by dgasmith** [comment]
Ok, that one may still be round tripping through task updates. Well, give it a day and see what pop out, we can revisit then.

**Comment by yudongqiu** [comment]
Sure I think the success rate is pretty high now :)

**Comment by dgasmith** [comment]
These are now all complete, closing.
